Fix *Method definitions in namespace document
w3c-ccg/security-vocab pull request #128
Opened 2021-12-18 22:45 UTC by clehner

Address #91.

- Change ids and IRIs for the following properties in the namespace document (web page) to correspond with the IRIs used in the Security Vocab and DID Core JSON-LD contexts:
  - authentication → authenticationMethod
  - capabilityDelegation → capabilityDelegationMethod
  - capabilityInvocation → capabilityInvocationMethod
  - keyAgreement → keyAgreementMethod
- Use both the short names (e.g. authentication) and the long names (e.g. authenticationMethod) in the headings. The short name is for consistency with use in JSON-LD documents with the existing context files, as an established convention; and the long name is for consistency with `assertionMethod` (which does not have this discrepancy) and with the IRI itself (which uses the long name as the suffix following the namespace part).
- Add notes about how/why it is this way.

2021-12-19 17:17 UTC, msporny requested changes
Minor change suggestion to remove explanation and place it elsewhere.

2021-12-19 17:17 UTC, msporny commented on index.html
> +        </p>
This presumes a tight coupling between DID Core and the Security Vocabulary. We shouldn't suggest that there is a tight coupling.

The Security Vocabulary doesn't need to make statements like this as how a JSON-LD context developer maps a term to a URL is entirely up to the context developer. That is, the Security Vocabulary could never know all the ways people map its URLs to terms. One developer may choose "authn" -> "https://w3id.org/security#authenticationMethod", while another chooses "验证" => "https://w3id.org/security#authenticationMethod" and another chooses "autenticación" => "https://w3id.org/security#authenticationMethod". All that to say, we shouldn't have this paragraph here. Sames goes for all the other entries.

If were were to add something to this effect somewhere, it should probably be in the DID Implementation Guide.

2021-12-19 17:17 UTC, msporny commented on index.html
> +        </p>
Same as comment above, needs to be removed.

2021-12-19 17:17 UTC, msporny commented on index.html
> +        </p>
Same as above, needs to be removed.

2021-12-19 17:17 UTC, msporny commented on index.html
> +        </p>
Same as above, needs to be removed.

2021-12-19 17:41 UTC, msporny commented
@clehner You identified something that I'm sure is going to be confusing to most people. I'm going to document it here because I'm not sure where the explanation should go, since it has to do w/ a number of standards.

Waaay back in the day, probably close to 10 years ago at this point, the security vocab was created to implement what has become (Linked) Data Proofs/Integrity today. Before DID Documents existed, we stored this information on files on Web servers (the documents look close to what did:web looks like today). The concept of a "verification method" dates back that far, and a persons "DID Document" at the time would state how the person would digitally sign statements that originate from them. That's where "assertionMethod" comes from... "this is the verification method you should use when you are checking to see if I have asserted something about the world." That "assertion about something about the world" became what's known today as Verifiable Credentials... [blog post about that here](http://manu.sporny.org/2014/credential-based-login/).

Due to the [push back of one big company at W3C back in 2013](http://manu.sporny.org/2013/lds-vs-jose/), we had to delay the standardization of (Linked) Data Proofs/Integrity by roughly 7 years, which means that we ended up standardizing Verifiable Credentials before we standardized some of the proof mechanisms (which was backwards, but that's standards politics for you). In that 7 years, people wrote code, used the security vocabulary, deployed proof of concepts, refined their libraries and the term people used for the verification method that should be used to check statements that you said about the world ended up being "assertionMethod"... and that's what got locked in when the Verifiable Credentials data model was standardized:

https://github.com/w3c/vc-data-model/blob/v1.1/contexts/credentials/v1#L193-L194

```
            "assertionMethod": {"@id": "sec:assertionMethod", "@type": "@id", "@container": "@set"},
            "authentication": {"@id": "sec:authenticationMethod", "@type": "@id", "@container": "@set"}
```

Some think we really should've gone with "assertion", but it was a bit too late to change it at that point given all the software that had been written with the older term. We could change it in the future in Verifiable Credentials 2.0, but then everyone would have to update their software. The people using JSON-LD would have an easier time that those that don't... but then the problem becomes not just updating VC implementations, but all the signature suite libraries as well. At the time, it was deemed "not worth it", and so "assertionMethod" stuck around while the newer terms dropped the "Method" suffix in the JSON-LD Contexts.

It's a minor annoyance for those of us that like consistent terminology, and it is the unfortunate side-effect of standards politics delaying the (Linked) Data Proofs/Integrity work coupled with implementers implementing and deploying software in a way that makes it hard to change the values that they've shipped. Hope that helps explain why things are the way they are today.

2021-12-20 23:28 UTC, OR13 approved these changes
Looks like the feedback was implemented. @msporny would you consider adding a PR with the language examples you provided here?

2021-12-21 14:46 UTC, msporny approved these changes

2021-12-21 14:50 UTC, msporny commented
> Looks like the feedback was implemented. 

This is ready to merge. 

> @msporny would you consider adding a PR with the language examples you provided here?

I'm going to hold off on doing any of that since there is active debate on where such language should go:

https://github.com/w3c/did-spec-registries/pull/392#issuecomment-997432278

This PR should be merged immediately since it fixes an obvious bug in the document.

2021-12-22 00:15 UTC, merged